### ISSUE TITLE
[Feature Request] Output Dir, and check if file is not allready there before extracting.

### ISSUE THREAD

**Issue by oursours** [arfoll/unrarall#10]
Hi, 

first of all thanks for the great work ! :)

This script is really nice and works perfectly for me.

I m just wondering if there is a way to specify an output dir ? ( i red carefully the doc but seems not ... ). That would be really nice if we could and also check if the file isn't allready extracted in the output directory.

Regards.

**Comment by xieem** [comment]
@delcypher so did this got implemented? If yes, how? Like the previous mentioned command? $ unrarall --clean=all --output ~/mystuff/ ~/Downloads ?

**Comment by delcypher** [comment]
@xieem I believe it was implemented. Read ``unrarall --help``.

**Comment by strider2112** [comment]
@xieem the output directory was implemented and is in the master file. It works just like how you're asking.

As for this advanced cleanup they last talked about, I'm not sure. I never downloaded an update since then.
