### ISSUE TITLE
'no rar files extracted' error

### ISSUE THREAD

**Issue by mkendrick** [arfoll/unrarall#18]
Hi. Found your script and have been attempting to get it to work on a FreeBSD-based NAS (FreeNAS).

Having some trouble, the script doesn't seem to find any rar files. Sample output:

[root@freenas] /mnt/vol1/tv/show# /mnt/vol1/backup/unrarall -d -v -s --clean=all /mnt/vol1/tv/show/test
Detecting clean up hooks...
Found unrarall-clean-covers_folders
Found unrarall-clean-empty_folders
Found unrarall-clean-nfo
Found unrarall-clean-osx_junk
Found unrarall-clean-rar
Found unrarall-clean-sample_folders
Found unrarall-clean-sample_videos
Found unrarall-clean-windows_junk
Using virtual clean-up hook all
Using "echo" to extract rar files
Working over directory "/mnt/vol1/tv/show/test"
no rar files extracted

There are, of course, many subfolders in my 'test' dir, all of which contain multi-part rar archives:

[root@freenas /mnt/vol1/tv/show/test/show.S07E13.HDTV.XviD]# ls
show.s07e13.hdtv.xvid.r03
show.s07e13.hdtv.xvid.r08
show.s07e13.hdtv.xvid.r13
show.s07e13.hdtv.xvid.nfo
show.s07e13.hdtv.xvid.r04 
show.s07e13.hdtv.xvid.r09 
show.s07e13.hdtv.xvid.r14
show.s07e13.hdtv.xvid.rar 
... etc  (yes, it's a complete rar set.)

Grateful any assistance.  The default shell for FreeNAS is csh, however I get the same result when I run bash and then run the script.  Note that if I run without the -d switch, I get the same end result, however it does report that it's found the unrar executable:

[root@freenas] /mnt/vol1/tv/show# /mnt/vol1/backup/unrarall -v -s --clean=all /mnt/vol1/tv/show/test
Detecting clean up hooks...
Found unrarall-clean-covers_folders
Found unrarall-clean-empty_folders
Found unrarall-clean-nfo
Found unrarall-clean-osx_junk
Found unrarall-clean-rar
Found unrarall-clean-sample_folders
Found unrarall-clean-sample_videos
Found unrarall-clean-windows_junk
Using virtual clean-up hook all
Looking for unrar...found
Using "unrar" to extract rar files
Working over directory "/mnt/vol1/tv/show/test"
no rar files extracted

other miscellanea:
UNRAR 4.20 freeware      Copyright (c) 1993-2012 Alexander Roshal
unrarall script version 0.4.2

**Comment by ashleyconnor** [comment]
If you are on OSX it might just be easier to install GNU findtools:

`brew install findutils --with-default-names`

Just make sure you unlink them after as it might cause issues.

**Comment by xieem** [comment]
@ashleyconnor how do you unlink them in the best way and what issues can they cause?

**Comment by ashleyconnor** [comment]
The only reason to unlink is that some other program that might not be expecting `GNU find` but `find` that comes on OSX.

To unlink run `brew unlink findutils` which will delete the symlinks out of your path. To relink just run `brew link findutils` again. You will probably need to reload your shell to make sure your paths are updated.

Unlinking shouldn't cause any issues unless another program depends on `GNU find`.

My output is below (*note* your homebrew path is likely to be different):

    ➜  aconnor  which find
    /opt/boxen/homebrew/bin/find
    ➜  aconnor  brew unlink findutils
    Unlinking /opt/boxen/homebrew/Cellar/findutils/4.4.2... 12 symlinks removed
    ➜  aconnor  which find
    /usr/bin/find

**Comment by mattmackenzie** [comment]
In 10.10.3, I just replaced all of the 'find' commands with 'gfind' from Homebrew

**Comment by Roedy86** [comment]
Hi, i had the same issue as mentioned above. (Freebsd 10.0 amd64)
I edited the file as described. added a -E after find and removed all backslashes in except the first in all find commands.

**Comment by alatas** [comment]
I tried @ashleyconnor solution to freebsd / freenas and succeed 
compiled findutils from ports ( https://www.freshports.org/misc/findutils/ )

`cd /usr/ports/misc/findutils/ && make install clean`

then change the script to `gfind` and it works :+1:

**Comment by delcypher** [comment]
Is this still an issue with the current `master`? If not I'll close this issue.

If someone would like to refactor the way we use `find` so that it works wtih macOS/*BSD `find` and GNU find that would be great. We have a test suite now so this should be way easier to test.

**Comment by delcypher** [comment]
In f00f48b09372734a048149178596ed9a90430b75 I taught unrarall to try and handle the different versions of `find` and use egrep style regular expressions so I'm closing. If this is still a problem please report the issue.

**Comment by xieem** [comment]
@delcypher seems to be working 100% here no more issue for me
