### ISSUE TITLE
"no rar files extracted"

### ISSUE THREAD

**Issue by xieem** [arfoll/unrarall#19]
Hi,

Every time I try to execute the command ./unrarall dir

the applications gives me "working over directory "dir"
no rar files extracted

while the dir is filled with sub folders that contain rar files.

Any idea what I am doing wrong? I got UnRar installed and cksfv. Running it on Yosemite Server.
The dir is on a second installed harddrive. I applied chmod. 

Kind regards,

Maxime

**Comment by delcypher** [comment]
Take a look at #18 It's likely you're not using the GNU version of ``find`` which is used extensively in ``unrarall``. 

We should really fix this by using``find`` in a POSIX compliant way so ``unrarall`` would work on OSX, FreeBSD, etc...

**Comment by xieem** [comment]
@delcypher it was indeed the "find" problem. Fixed it with the solution provided in #18 

One last question, can this script also be applied on Network Drives (for autodelete)? (AFP and such?)

**Comment by arfoll** [comment]
As long as it's mounted and you have RW access it should work but I've never used AFP so not sure how OS X treats it. You can always try with `--dry` first.

**Comment by xieem** [comment]
@arfoll I think I should have been a bit more specific, I mean Synology Drives are ony of that kind.

Nevertheless I'll try with --dry command. Thanks!
