### ISSUE TITLE
What happens if I run the command twice?

### ISSUE THREAD

**Issue by meffect** [arfoll/unrarall#27]
If I run this command twice

    /home/user/.script/unrarall -s --clean=all /source_parent_dir

Will the second run of the script not overlap the first command?

I'm thinking in the situation, where I want a cron job to run the command every 1 minute. The first run may still be processing when the second cron kicks off

**Comment by meffect** [comment]
I guess I can use http://linux.die.net/man/1/flock ... seems to be a better approach than implementing something in each individual program

**Comment by delcypher** [comment]
@meffect It's not safe to run multiple copies of unrarall at the same time. Using something like ``flock`` seems like a good idea as I don't want to add additional code to unrarall to detect for this.

**Comment by meffect** [comment]
Sounds good. Good to know it's not built in, so I can account for it
