### ISSUE TITLE
How to run cleanup over directories that dont contain rars?

### ISSUE THREAD

**Issue by meffect** [arfoll/unrarall#28]
How to run cleanup over directories that dont contain rars?

Sometimes my sub folders/files never downloaded as rars. but they still have the sample and .nfo, etc. Can this script be configured to clean those up? It seems to be ignoring them right now

**Comment by delcypher** [comment]
@meffect This is not something `unrarall` is designed to support. You could of course hack `unrarall`'s code to run the hooks in every directory recursively but this isn't something I think `unrarall` should support unless we can come up with a sane way to do this that doesn't over complicate the code.

You're welcome to try.

**Comment by meffect** [comment]
I wonder how best do it. unrarall's most common use case this is very common issue I would think

**Comment by delcypher** [comment]
@meffect 

At a guess we'd probably want a `--no-extract` flag that changes `unrarall`'s behaviour. In the script the hooks would be run on every directory recursively (bottom up).

I don't have the time to implement this but you're welcome to try.
