### ISSUE TITLE
Corrupt File or wrong password Error

### ISSUE THREAD

**Issue by G4ME** [arfoll/unrarall#29]
I have a folder with multiple rar archieves split into parts. When I try to extract them with ./unrarall -s path/to/files I get the error "Corrupt file or wrong password". So I checked /home/user/.unrar_passwords for the correct password. This file is per line right?

Here is the output I get when running the command. Please note that when I run `unrar e xxx.part01.rar` it works(same password, same archieve)

`pi@mmc:/path/to/files $ ./unrarall -s Dir\ with\ some\ spaces\ between/
Working over directory "Dir with some spaces between/"
Extracting (e) "Dir with some spaces between/file-se.part01.rar"...
Checksum error in the encrypted file /path/to/files/Dir\ with\ some\ spaces\ between/file-se.part01.rar. Corrupt file or wrong password.`

Anyone got an idea?

**Comment by arfoll** [comment]
Closing as no more info
