### ISSUE TITLE
FR: Move subtitle files to main dir

### ISSUE THREAD

**Issue by Ruvetuve** [arfoll/unrarall#32]
Hi,

Unrarring sub files goes well (needs a couple of unpack iterations). I want to automatically move IDX, SUB and SRT files from the Subs directory to the main directory of the video/rar file(s).

Can this be added? Thanks!

**Comment by delcypher** [comment]
@Ruvetuve You can write a clean up hook to do this. See the `unrarall_clean_*` functions in the script (also see the `HACKING` file) . If you get it working feel free to create a pull request for this feature.

**Comment by Ruvetuve** [comment]
Hehe guess what. Create this hoor today! Nice timing haha.  I'll see how I can add this hoor to a pull request. Thanks
