### ISSUE TITLE
Clobbering files on extraction and skipping already extracted files 

### ISSUE THREAD

**Issue by delcypher** [arfoll/unrarall#37]
PRs #34 and #30 both try to make unrarall avoid extracting already extracted files.

Issue #31 reported problems where unrarall would clobber existing rar files upon extraction.

These problems are not independent of each and so they should be tackled together.

Ideally we

* Should not clobber existing files that come from existing archives. E.g. If `a.rar` contains `foo` and `b.rar` contains a different `foo` and we use the `--output` flag we'll only end up with one `foo` file as one will be written over the other. We should avoid this.

* We should handle rar files within rar files (i.e. do recursive extract up to some bound) and should not clobber existing rar files when we do the extraction.

* We should have an option to avoid extracting already extracted files.

The solution to these problems would probably involve examining the archive contents before extracting, always doing extraction in a temporary folder and have a sensible scheme for handling clobbering that emits a warning and tries to carry on by writing the conflicting files somewhere else.

I don't have time to work on this but if anyone wants to tackle this task that would be great.

**Comment by arfoll** [comment]
Done & merged
