### ISSUE TITLE
extraction fails if source folder name has spaces

### ISSUE THREAD

**Issue by marc-aurel** [arfoll/unrarall#38]
If the folder where the rar-files lie has a name containing spaces extraction fails with error:

cd /test/**Rhap\ sodies/**
unrarall -v --full-path --clean=rar .

          Cannot open /test/Rhap.rar
          File or folder not found
          No files to extract

`unrar x <filename>.part1.rar ` in same folder works flawlessly

**Comment by delcypher** [comment]
@marc-aurel Thanks for reporting. I've confirmed this. I've written a test case and a fix in #39. I'm waiting for the build to succeed. If it does then I'll merge it.

**Comment by marc-aurel** [comment]
same problem occurs if filenames have spaces

**Comment by delcypher** [comment]
@marc-aurel Is that with #39 ? I added test cases for this in f92b8b89604fcad8c0b75e101f328f3e74cf84e4 and everything works fine.

**Comment by delcypher** [comment]
@marc-aurel #39 is now merged into `master`. Can you confirm if you're still having problems with `unrarall` on the `master` branch?

**Comment by marc-aurel** [comment]
I can confirm that it works now with file and folder names that have special characters like spaces and brackets.
Fantastic! Thanks a lot.
