### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by marc-aurel** [arfoll/unrarall#41]
please introduce 2 further parameters:

- recursive yes/no:
  to choose if only files in current directory are used or if also subdirectories are treated
- overwrite warning yes/no:
   ask user if file can be overwritten.
   unrarall currently ALWAYS overwrites existing files bearing the same path of extracted files.

**Comment by arfoll** [comment]
Implemented with "--skip-if-exists" flag. Also the "--depth" flag does the recursivness?
