### ISSUE TITLE
Unnrar from subfolders and rename extracted file to parent folder name

### ISSUE THREAD

**Issue by SpeedyLR** [arfoll/unrarall#55]
Hello,

A very useful script, thank you so much!

But is it possible, if a file is extracted in a subdirectory, to rename it to the name of the subdirectory?

Thanks

**Comment by arfoll** [comment]
Unless you have a good idea how to achieve this, I would avoid doing so as there are often more than one files in an archive, it gets quite complicated to 'guess' what the content of the archive is
