### ISSUE TITLE
line 45 - grep

### ISSUE THREAD

**Issue by dellorianes** [arfoll/unrarall#57]
First o all, thank you very much for our share. I was searching something like this time ago.

I have the following error when runing the script.

line 45: grep:: command not found
[31mInsufficient number of arguments. See script --help[0m

Any help?

Thank you

**Comment by arfoll** [comment]
I've noticed this as well :/ I fear something changed recently in coreutils and may or not be backwards compatible with other things...

Try the fix in the branch linked - I'll kick travis to rerun the tests, seems it's been disabled recently.

**Comment by blackandcold** [comment]
can confirm the removal of the escape backslash resolves the issue.
Really odd. As if the interpreter (bash?!) changed.

Why is the command in quotes anyway?
