### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by SpaceAgeHero** [arfoll/unrarall#58]
Hey,

for some reason this script stopped working for me after some years of usage on my aarch64 linux installation. It no longer extracts any rar files.
Any idea how to narrow down the issue? No rights have been changed. What are the dependencies actually?

Skipping file "(actual file)" because it does not appear to be a valid rar file.
no rar files extracted

**Comment by arfoll** [comment]
Try the branch https://github.com/arfoll/unrarall/commits/issue-57. The reason I haven't committed this to master is that it's a slightly weird behaviour change in coreutils/bash and I have no idea how to test the behaviour :/ I wanted to investigate a bit more but ended up on other topics. I may merge it as it's clearly the more common behaviour these days or just write a simplisitic test to avoid this.

Let me know if that fixes it and merry christmas!

**Comment by SpaceAgeHero** [comment]
Thanks for they quick reply. Just tried it but didn't work either.
:-/
Merry Christmas for you too!

**Comment by arfoll** [comment]
The deps are real basic, you need bash, coreutils, sed & grep and then at least one of unrar, rar or 7z, it defaults to unrar. You can add -v to run in verbose mode which might give us a hint. I just tried it on arch and it works as expected, quick little test like:

`
$ mkdir /tmp/test/
$ cd /tmp/test
$ dd if=/dev/zero of=output bs=1M count=50
$ rar a output.rar output
$ unrarall -v .
`

Here's what I have on my arch box (i'll try update the laptop later and can double check):
`
bash 5.2.037-1
grep 3.11-1
sed 4.9-3
unrar 1:7.1.1-1
coreutils 9.5-2
`

**Comment by arfoll** [comment]
So I found the issue - it's an update to the file package recently that I use to identify if it's a rar file, the mime type reported changed from (file-5.45-1):
```
$ file --mime output.rar
output.rar: application/x-rar; charset=binary
```

to (file-5.46-2):
```
$ file --mime output.rar    
output.rar: application/vnd.rar; charset=binary
```

line 782 you can quickly fix this by changing to vnd.rar as the MATCHRARMIME var. I'll come up with a better fix in a bit.

**Comment by arfoll** [comment]
I pushed a fix in master, if you can just quickly test it would be appreciated, but i'm pretty sure it works :)

**Comment by SpaceAgeHero** [comment]
Yes! It's working again. Thank you.
Please allow one more question. I've been running this with the "--clean=all" parameter but suddenly this also removes .nfo files. According to "unrarall -h" it's working as expected but I thought this retained .nfo files up to now ...
Is there a way to run all hooks but keep .nfo / SUB folders?

**Comment by arfoll** [comment]
Glad it works!

You can individually ask for the hooks, you're using 'all' which runs all of them, maybe we had a bug for nfo files at some point, but basically just list the ones you want:
```
unrarall --clean=rar,sample_videos,osx_junk <folder>
```
The hook list is at the bottom of the help file, it maybe could do with a cleanup...

Truth be told, maybe just rar is a good default to just clean, I recommend the combo of --dry and --verbose, this will help you understand what it's actually removing if you have any doubts.
